CREATE TABLE audit_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(80) NOT NULL,
    target_id BIGINT NOT NULL,
    admin_id BIGINT REFERENCES users (id),
    result VARCHAR(40) NOT NULL,
    reason TEXT,
    rule_summary TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_audit_records_result CHECK (result IN ('APPROVED', 'REJECTED'))
);

CREATE INDEX idx_audit_records_target
    ON audit_records (target_type, target_id, created_at DESC);

CREATE INDEX idx_audit_records_admin
    ON audit_records (admin_id, created_at DESC);

CREATE TABLE rule_hit_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(80) NOT NULL,
    target_id BIGINT,
    rule_type VARCHAR(80) NOT NULL,
    rule_code VARCHAR(120) NOT NULL,
    matched_text_hash VARCHAR(128),
    severity VARCHAR(40) NOT NULL,
    decision_hint VARCHAR(80) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_rule_hit_records_severity CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'BLOCK')),
    CONSTRAINT ck_rule_hit_records_decision_hint CHECK (decision_hint IN ('ALLOW', 'REVIEW', 'REJECT'))
);

CREATE INDEX idx_rule_hit_records_target
    ON rule_hit_records (target_type, target_id, created_at DESC);

CREATE TABLE forbidden_terms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term VARCHAR(120) NOT NULL,
    term_type VARCHAR(60) NOT NULL,
    severity VARCHAR(40) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_by_admin_id BIGINT REFERENCES users (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_forbidden_terms_term UNIQUE (term),
    CONSTRAINT ck_forbidden_terms_type CHECK (term_type IN ('KEYWORD', 'CATEGORY')),
    CONSTRAINT ck_forbidden_terms_severity CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'BLOCK'))
);

CREATE INDEX idx_forbidden_terms_enabled
    ON forbidden_terms (enabled, severity, term);
