-- ========================================================================
-- V10: 商品审核规则体系（audit_records / rule_hit_records / forbidden_terms）
-- ========================================================================
-- 设计目标：
--   1. 构建"机审初筛 → 人审定论"的双保险内容审核链路。
--      - forbidden_terms：管理员动态维护的敏感词库，支持即时生效。
--      - rule_hit_records：后端自动关键词匹配的命中记录，可审计追溯。
--      - audit_records：管理员人工审核的结论记录。
--   2. 审核维度与商品业务维度彻底解耦。
--      - target_type + target_id 的泛化设计可复用于多种审核场景。
--   3. 每一条规则命中都持久化，支持事后复盘和风控升级。
--   4. severity 分级（LOW/MEDIUM/HIGH/BLOCK）配合 decision_hint
--      （ALLOW/REVIEW/REJECT）实现细粒度的自动化裁决建议。
-- ========================================================================

-- ------------------------------------------------------------------------
-- 人工审核记录表
-- 设计要点：
--   - target_type + target_id：泛化设计，支持审核商品、用户、评论等多种目标
--   - admin_id：执行审核的管理员（可为空，表示系统自动判定）
--   - result：APPROVED 或 REJECTED，二值判定避免模糊地带
--   - reason：审核理由，管理员手动填写
--   - rule_summary：关联的规则命中摘要，便于追溯审核依据
--   - 与 rule_hit_records 配合使用：管理员查看自动命中记录后作出审核判定
-- ------------------------------------------------------------------------
CREATE TABLE audit_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(80) NOT NULL,                         -- 审核目标类型（如 'GOODS'、'USER'）
    target_id BIGINT NOT NULL,                                -- 审核目标 ID
    admin_id BIGINT REFERENCES users (id),                    -- 审核管理员（可空，表示系统触发）
    result VARCHAR(40) NOT NULL,                              -- 审核结果：APPROVED / REJECTED
    reason TEXT,                                              -- 审核理由或备注
    rule_summary TEXT,                                        -- 关联的规则命中摘要（便于追溯）
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ck_audit_records_result CHECK (result IN ('APPROVED', 'REJECTED'))
);

-- 按目标类型+ID+时间降序查询该目标的所有审核历史
CREATE INDEX idx_audit_records_target
    ON audit_records (target_type, target_id, created_at DESC);

-- 按管理员查询其处理过的审核记录
CREATE INDEX idx_audit_records_admin
    ON audit_records (admin_id, created_at DESC);

-- ------------------------------------------------------------------------
-- 规则命中记录表（自动化风控引擎的输出）
-- 设计要点：
--   - 每次关键词/规则匹配成功后写入一条记录，形成可审计的裁决轨迹
--   - rule_code：规则标识，便于归类统计（如 'FORBIDDEN_TERM_考试答案'）
--   - matched_text_hash：命中文本的哈希值，不存明文避免敏感信息泄漏
--   - severity + decision_hint：双重分级体系
--     · severity（严重程度）：LOW→MEDIUM→HIGH→BLOCK
--     · decision_hint（决策建议）：ALLOW(放行) / REVIEW(人工复核) / REJECT(直接拒绝)
--   - 即使商品最终被人工放行，命中记录依然保留，用于：
--     a) 风控策略效果评估（命中率、误杀率）
--     b) 卖家信用画像（累计命中次数）
-- ------------------------------------------------------------------------
CREATE TABLE rule_hit_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(80) NOT NULL,                         -- 命中目标类型（如 'GOODS'）
    target_id BIGINT,                                         -- 命中目标 ID（可为空，表示仅规则层面命中）
    rule_type VARCHAR(80) NOT NULL,                           -- 规则分类（如 'FORBIDDEN_TERM'、'PRICE_ANOMALY'）
    rule_code VARCHAR(120) NOT NULL,                          -- 规则标识码（如 'FORBIDDEN_TERM_考试答案'）
    matched_text_hash VARCHAR(128),                           -- 命中文本的 SHA-256 哈希（不存明文）
    severity VARCHAR(40) NOT NULL,                            -- 严重程度：LOW / MEDIUM / HIGH / BLOCK
    decision_hint VARCHAR(80) NOT NULL,                       -- 决策建议：ALLOW / REVIEW / REJECT
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ck_rule_hit_records_severity CHECK (
        severity IN ('LOW', 'MEDIUM', 'HIGH', 'BLOCK')
    ),
    CONSTRAINT ck_rule_hit_records_decision_hint CHECK (
        decision_hint IN ('ALLOW', 'REVIEW', 'REJECT')
    )
);

-- 按目标类型+ID+时间降序查询某目标的所有规则命中
CREATE INDEX idx_rule_hit_records_target
    ON rule_hit_records (target_type, target_id, created_at DESC);

-- ------------------------------------------------------------------------
-- 敏感词库（forbidden_terms）
-- 设计要点：
--   - 由管理员动态维护，无需重启服务即可生效
--   - term_type 区分 KEYWORD（关键词）和 CATEGORY（品类级禁用）
--   - severity 梯度：LOW→MEDIUM→HIGH→BLOCK
--     · BLOCK 级命中直接拒绝发布
--     · HIGH 级命中强制进入人工审核
--     · MEDIUM/LOW 级命中记录但不阻断
--   - enabled 开关：可临时关闭某敏感词而不删除记录
--   - UNIQUE(term)：防止重复添加同一敏感词
--   - created_by_admin_id：追溯操作管理员，满足安全审计要求
-- ------------------------------------------------------------------------
CREATE TABLE forbidden_terms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term VARCHAR(120) NOT NULL,                               -- 敏感词/短语
    term_type VARCHAR(60) NOT NULL,                           -- 类型：KEYWORD(关键词) / CATEGORY(品类)
    severity VARCHAR(40) NOT NULL,                            -- 严重程度：LOW / MEDIUM / HIGH / BLOCK
    enabled BOOLEAN NOT NULL DEFAULT TRUE,                    -- 是否启用，关闭后该词不参与匹配
    created_by_admin_id BIGINT REFERENCES users (id),         -- 创建该词的管理员
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_forbidden_terms_term UNIQUE (term),         -- 同一敏感词不允许重复
    CONSTRAINT ck_forbidden_terms_type CHECK (
        term_type IN ('KEYWORD', 'CATEGORY')
    ),
    CONSTRAINT ck_forbidden_terms_severity CHECK (
        severity IN ('LOW', 'MEDIUM', 'HIGH', 'BLOCK')
    )
);

-- 快速查询已启用的敏感词，按严重程度排序（BLOCK 级优先匹配）
CREATE INDEX idx_forbidden_terms_enabled
    ON forbidden_terms (enabled, severity, term);