CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receiver_user_id BIGINT NOT NULL REFERENCES users (id),
    type VARCHAR(80) NOT NULL,
    title VARCHAR(120) NOT NULL,
    content TEXT NOT NULL,
    related_type VARCHAR(80),
    related_id BIGINT,
    dedupe_key VARCHAR(160),
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_notifications_type CHECK (type IN (
        'ORDER_CREATED',
        'ORDER_SELLER_CONFIRMED',
        'PAYMENT_ESCROWED',
        'COMPLETION_REQUESTED',
        'ORDER_COMPLETED',
        'SETTLEMENT_STATUS_CHANGED'
    )),
    CONSTRAINT ck_notifications_related CHECK (
        (related_type IS NULL AND related_id IS NULL)
            OR (related_type IS NOT NULL AND related_id IS NOT NULL)
    )
);

CREATE INDEX idx_notifications_receiver_created
    ON notifications (receiver_user_id, created_at DESC);

CREATE INDEX idx_notifications_receiver_unread
    ON notifications (receiver_user_id, created_at DESC)
    WHERE read_at IS NULL;

CREATE UNIQUE INDEX uq_notifications_receiver_dedupe
    ON notifications (receiver_user_id, dedupe_key)
    WHERE dedupe_key IS NOT NULL;

ALTER TABLE stored_files
    DROP CONSTRAINT IF EXISTS ck_stored_files_file_kind;

ALTER TABLE stored_files
    ADD CONSTRAINT ck_stored_files_file_kind
    CHECK (file_kind IN ('AVATAR', 'GOODS_IMAGE', 'CAMPUS_AUTH_MATERIAL', 'ORDER_EVIDENCE'));

ALTER TABLE stored_files
    ADD CONSTRAINT ck_stored_files_order_evidence_private
    CHECK (file_kind <> 'ORDER_EVIDENCE' OR visibility_scope = 'PRIVATE');
