CREATE TABLE trade_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(40) NOT NULL,
    goods_id BIGINT NOT NULL REFERENCES goods (id),
    buyer_id BIGINT NOT NULL REFERENCES users (id),
    seller_id BIGINT NOT NULL REFERENCES users (id),
    conversation_id BIGINT,
    accepted_bargain_card_id BIGINT,
    frozen_amount NUMERIC(12,2) NOT NULL,
    status VARCHAR(40) NOT NULL,
    trade_place_id BIGINT REFERENCES campus_places (id),
    trade_place_detail VARCHAR(255),
    meetup_time TIMESTAMPTZ,
    buyer_note VARCHAR(500),
    seller_payout_account_snapshot_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    closed_at TIMESTAMPTZ,
    CONSTRAINT uq_trade_orders_order_no UNIQUE (order_no),
    CONSTRAINT ck_trade_orders_status CHECK (status IN (
        'PENDING_SELLER_CONFIRM',
        'PENDING_PAYMENT',
        'PAID_PENDING_MEETUP',
        'COMPLETED_PENDING_SETTLEMENT',
        'COMPLETED',
        'CANCELLED',
        'CLOSED',
        'DISPUTE_PROCESSING',
        'REFUND_PROCESSING'
    )),
    CONSTRAINT ck_trade_orders_frozen_amount CHECK (frozen_amount >= 0.01),
    CONSTRAINT ck_trade_orders_parties CHECK (buyer_id <> seller_id)
);

CREATE UNIQUE INDEX uq_trade_orders_goods_occupying
    ON trade_orders (goods_id)
    WHERE status IN (
        'PENDING_SELLER_CONFIRM',
        'PENDING_PAYMENT',
        'PAID_PENDING_MEETUP',
        'DISPUTE_PROCESSING',
        'REFUND_PROCESSING'
    );

CREATE INDEX idx_trade_orders_buyer_created
    ON trade_orders (buyer_id, created_at DESC);

CREATE INDEX idx_trade_orders_seller_created
    ON trade_orders (seller_id, created_at DESC);

CREATE INDEX idx_trade_orders_goods
    ON trade_orders (goods_id);

ALTER TABLE goods
    ADD CONSTRAINT fk_goods_current_occupied_order
    FOREIGN KEY (current_occupied_order_id) REFERENCES trade_orders (id);

CREATE INDEX idx_goods_current_occupied_order
    ON goods (current_occupied_order_id);

CREATE TABLE order_state_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES trade_orders (id) ON DELETE CASCADE,
    from_status VARCHAR(40),
    to_status VARCHAR(40) NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    operator_user_id BIGINT REFERENCES users (id),
    operator_admin_id BIGINT REFERENCES users (id),
    reason VARCHAR(500),
    metadata_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_order_state_records_order_created
    ON order_state_records (order_id, created_at, id);

CREATE TABLE completion_confirmation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES trade_orders (id) ON DELETE CASCADE,
    seller_id BIGINT NOT NULL REFERENCES users (id),
    buyer_id BIGINT NOT NULL REFERENCES users (id),
    status VARCHAR(40) NOT NULL,
    window_starts_at TIMESTAMPTZ NOT NULL,
    window_ends_at TIMESTAMPTZ NOT NULL,
    confirmed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_completion_requests_status CHECK (status IN ('PENDING', 'CONFIRMED', 'EXPIRED', 'CANCELLED')),
    CONSTRAINT ck_completion_requests_window CHECK (window_ends_at > window_starts_at)
);

CREATE UNIQUE INDEX uq_completion_requests_order_pending
    ON completion_confirmation_requests (order_id)
    WHERE status = 'PENDING';

CREATE TABLE payment_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_no VARCHAR(40) NOT NULL,
    order_id BIGINT NOT NULL REFERENCES trade_orders (id) ON DELETE CASCADE,
    amount NUMERIC(12,2) NOT NULL,
    status VARCHAR(40) NOT NULL,
    provider VARCHAR(40) NOT NULL,
    provider_payload_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    paid_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    CONSTRAINT uq_payment_orders_payment_no UNIQUE (payment_no),
    CONSTRAINT ck_payment_orders_status CHECK (status IN ('PENDING', 'PROCESSING', 'ESCROWED', 'FAILED', 'CLOSED')),
    CONSTRAINT ck_payment_orders_amount CHECK (amount >= 0.01)
);

CREATE UNIQUE INDEX uq_payment_orders_order_active
    ON payment_orders (order_id)
    WHERE status IN ('PENDING', 'PROCESSING');

CREATE INDEX idx_payment_orders_order
    ON payment_orders (order_id);

CREATE TABLE payment_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_order_id BIGINT NOT NULL REFERENCES payment_orders (id) ON DELETE CASCADE,
    transaction_no VARCHAR(60) NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    status VARCHAR(40) NOT NULL,
    provider VARCHAR(40) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    raw_summary_json JSONB,
    CONSTRAINT uq_payment_transactions_no UNIQUE (transaction_no),
    CONSTRAINT ck_payment_transactions_amount CHECK (amount >= 0.01)
);

CREATE TABLE payment_callback_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_order_id BIGINT REFERENCES payment_orders (id) ON DELETE SET NULL,
    provider VARCHAR(40) NOT NULL,
    callback_no VARCHAR(80) NOT NULL,
    payload_hash VARCHAR(128) NOT NULL,
    processed_status VARCHAR(40) NOT NULL,
    processed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_payment_callback_logs_provider_no UNIQUE (provider, callback_no)
);

CREATE TABLE settlement_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES trade_orders (id) ON DELETE CASCADE,
    payment_order_id BIGINT NOT NULL REFERENCES payment_orders (id),
    settlement_no VARCHAR(40) NOT NULL,
    settlement_amount NUMERIC(12,2) NOT NULL,
    status VARCHAR(40) NOT NULL,
    freeze_started_at TIMESTAMPTZ NOT NULL,
    freeze_ends_at TIMESTAMPTZ NOT NULL,
    settled_at TIMESTAMPTZ,
    failure_reason VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_settlement_records_order UNIQUE (order_id),
    CONSTRAINT uq_settlement_records_no UNIQUE (settlement_no),
    CONSTRAINT ck_settlement_records_status CHECK (status IN ('PENDING', 'PROCESSING', 'SETTLED', 'FAILED', 'CLOSED')),
    CONSTRAINT ck_settlement_records_amount CHECK (settlement_amount >= 0.01),
    CONSTRAINT ck_settlement_records_freeze CHECK (freeze_ends_at > freeze_started_at)
);

CREATE INDEX idx_settlement_records_status_freeze
    ON settlement_records (status, freeze_ends_at);

CREATE TABLE settlement_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_record_id BIGINT NOT NULL REFERENCES settlement_records (id) ON DELETE CASCADE,
    attempt_no INTEGER NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    status VARCHAR(40) NOT NULL,
    payout_account_id BIGINT,
    payout_account_snapshot_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    provider_attempt_no VARCHAR(80),
    failure_reason VARCHAR(500),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    created_by_admin_id BIGINT REFERENCES users (id),
    CONSTRAINT uq_settlement_attempts_attempt_no UNIQUE (settlement_record_id, attempt_no),
    CONSTRAINT ck_settlement_attempts_status CHECK (status IN ('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED')),
    CONSTRAINT ck_settlement_attempts_amount CHECK (amount >= 0.01)
);

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES trade_orders (id) ON DELETE CASCADE,
    reviewer_id BIGINT NOT NULL REFERENCES users (id),
    reviewed_user_id BIGINT NOT NULL REFERENCES users (id),
    rating INTEGER NOT NULL,
    content VARCHAR(500),
    status VARCHAR(40) NOT NULL,
    submitted_at TIMESTAMPTZ NOT NULL,
    modified_until TIMESTAMPTZ NOT NULL,
    visible_at TIMESTAMPTZ,
    hidden_by_admin_id BIGINT REFERENCES users (id),
    hidden_reason VARCHAR(500),
    CONSTRAINT uq_reviews_order_reviewer UNIQUE (order_id, reviewer_id),
    CONSTRAINT ck_reviews_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT ck_reviews_status CHECK (status IN ('SUBMITTED', 'VISIBLE', 'HIDDEN', 'EXCLUDED')),
    CONSTRAINT ck_reviews_parties CHECK (reviewer_id <> reviewed_user_id)
);

CREATE INDEX idx_reviews_reviewed_user
    ON reviews (reviewed_user_id, submitted_at DESC);
