ALTER TABLE notifications
    DROP CONSTRAINT IF EXISTS ck_notifications_type;

ALTER TABLE notifications
    ADD CONSTRAINT ck_notifications_type CHECK (type IN (
        'ORDER_CREATED',
        'ORDER_SELLER_CONFIRMED',
        'PAYMENT_ESCROWED',
        'COMPLETION_REQUESTED',
        'ORDER_COMPLETED',
        'SETTLEMENT_STATUS_CHANGED',
        'REPORT_SUBMITTED',
        'REPORT_RESOLVED',
        'APPEAL_REVIEWED',
        'REFUND_STATUS_CHANGED',
        'PENALTY_APPLIED'
    ));

ALTER TABLE stored_files
    DROP CONSTRAINT IF EXISTS ck_stored_files_file_kind;

ALTER TABLE stored_files
    ADD CONSTRAINT ck_stored_files_file_kind
    CHECK (file_kind IN ('AVATAR', 'GOODS_IMAGE', 'CAMPUS_AUTH_MATERIAL', 'ORDER_EVIDENCE', 'REPORT_EVIDENCE', 'APPEAL_EVIDENCE'));

ALTER TABLE stored_files
    DROP CONSTRAINT IF EXISTS ck_stored_files_order_evidence_private;

ALTER TABLE stored_files
    ADD CONSTRAINT ck_stored_files_governance_evidence_private
    CHECK (file_kind NOT IN ('ORDER_EVIDENCE', 'REPORT_EVIDENCE', 'APPEAL_EVIDENCE') OR visibility_scope = 'PRIVATE');

CREATE TABLE favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    goods_id BIGINT NOT NULL REFERENCES goods (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_favorites_user_goods UNIQUE (user_id, goods_id)
);

CREATE INDEX idx_favorites_user_created
    ON favorites (user_id, created_at DESC);

CREATE TABLE follows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    followed_user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_follows_pair UNIQUE (follower_id, followed_user_id),
    CONSTRAINT ck_follows_not_self CHECK (follower_id <> followed_user_id)
);

CREATE INDEX idx_follows_follower_created
    ON follows (follower_id, created_at DESC);

CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id BIGINT NOT NULL REFERENCES users (id),
    target_type VARCHAR(32) NOT NULL,
    target_id BIGINT NOT NULL,
    reason_type VARCHAR(60) NOT NULL,
    description VARCHAR(1500) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
    priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    merged_into_report_id BIGINT REFERENCES reports (id),
    handled_by_admin_id BIGINT REFERENCES users (id),
    handled_at TIMESTAMPTZ,
    handling_note VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_reports_target_type CHECK (target_type IN ('GOODS', 'ORDER', 'USER')),
    CONSTRAINT ck_reports_status CHECK (status IN ('PENDING', 'PROCESSING', 'UPHELD', 'REJECTED', 'CLOSED')),
    CONSTRAINT ck_reports_priority CHECK (priority IN ('NORMAL', 'HIGH'))
);

CREATE INDEX idx_reports_status_priority_created
    ON reports (status, priority, created_at DESC);

CREATE INDEX idx_reports_reporter_created
    ON reports (reporter_id, created_at DESC);

CREATE TABLE report_evidence_files (
    report_id BIGINT NOT NULL REFERENCES reports (id) ON DELETE CASCADE,
    file_id BIGINT NOT NULL REFERENCES stored_files (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (report_id, file_id)
);

CREATE TABLE appeals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL REFERENCES reports (id),
    appellant_id BIGINT NOT NULL REFERENCES users (id),
    description VARCHAR(1500) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING_REVIEW',
    reviewed_by_admin_id BIGINT REFERENCES users (id),
    reviewed_at TIMESTAMPTZ,
    review_note VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_appeals_status CHECK (status IN ('PENDING_REVIEW', 'APPROVED', 'REJECTED', 'CLOSED'))
);

CREATE INDEX idx_appeals_status_created
    ON appeals (status, created_at DESC);

CREATE INDEX idx_appeals_appellant_created
    ON appeals (appellant_id, created_at DESC);

CREATE TABLE appeal_evidence_files (
    appeal_id BIGINT NOT NULL REFERENCES appeals (id) ON DELETE CASCADE,
    file_id BIGINT NOT NULL REFERENCES stored_files (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (appeal_id, file_id)
);

CREATE TABLE refund_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_no VARCHAR(40) NOT NULL,
    order_id BIGINT NOT NULL REFERENCES trade_orders (id),
    payment_order_id BIGINT REFERENCES payment_orders (id),
    requested_by_user_id BIGINT NOT NULL REFERENCES users (id),
    amount NUMERIC(12,2) NOT NULL,
    refund_type VARCHAR(20) NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
    decision_by_admin_id BIGINT REFERENCES users (id),
    decision_note VARCHAR(1000),
    processed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_refund_orders_no UNIQUE (refund_no),
    CONSTRAINT ck_refund_orders_type CHECK (refund_type IN ('FULL', 'PARTIAL')),
    CONSTRAINT ck_refund_orders_status CHECK (status IN ('PENDING', 'PROCESSING', 'REFUNDED', 'FAILED', 'CLOSED')),
    CONSTRAINT ck_refund_orders_amount CHECK (amount >= 0.01)
);

CREATE INDEX idx_refund_orders_requester_created
    ON refund_orders (requested_by_user_id, created_at DESC);

CREATE INDEX idx_refund_orders_status_created
    ON refund_orders (status, created_at DESC);

CREATE TABLE penalty_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    report_id BIGINT REFERENCES reports (id),
    appeal_id BIGINT REFERENCES appeals (id),
    penalty_type VARCHAR(40) NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_by_admin_id BIGINT NOT NULL REFERENCES users (id),
    lifted_by_admin_id BIGINT REFERENCES users (id),
    lifted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_penalty_records_type CHECK (penalty_type IN ('WARNING', 'TRADE_RESTRICT', 'ACCOUNT_LOCK')),
    CONSTRAINT ck_penalty_records_status CHECK (status IN ('ACTIVE', 'LIFTED'))
);

CREATE INDEX idx_penalty_records_user_status
    ON penalty_records (user_id, status, created_at DESC);

CREATE TABLE credit_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    source_type VARCHAR(40) NOT NULL,
    source_id BIGINT,
    reason VARCHAR(500) NOT NULL,
    internal_delta_value INTEGER NOT NULL DEFAULT 0,
    internal_level_before VARCHAR(20),
    internal_level_after VARCHAR(20),
    public_label VARCHAR(80) NOT NULL,
    created_by_admin_id BIGINT REFERENCES users (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_credit_records_source_type CHECK (source_type IN ('ORDER', 'REVIEW', 'REPORT', 'APPEAL', 'REFUND', 'MANUAL'))
);

CREATE INDEX idx_credit_records_user_created
    ON credit_records (user_id, created_at DESC);

CREATE TABLE credit_summaries (
    user_id BIGINT PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    fulfillment_count INTEGER NOT NULL DEFAULT 0,
    on_time_meetup_count INTEGER NOT NULL DEFAULT 0,
    positive_review_count INTEGER NOT NULL DEFAULT 0,
    negative_event_count INTEGER NOT NULL DEFAULT 0,
    public_tags_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    internal_score INTEGER NOT NULL DEFAULT 80,
    internal_level VARCHAR(20) NOT NULL DEFAULT 'B',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
