CREATE TABLE conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goods_id BIGINT NOT NULL REFERENCES goods (id),
    buyer_id BIGINT NOT NULL REFERENCES users (id),
    seller_id BIGINT NOT NULL REFERENCES users (id),
    status VARCHAR(40) NOT NULL DEFAULT 'NORMAL',
    last_message_id BIGINT,
    last_message_at TIMESTAMPTZ,
    buyer_archived_at TIMESTAMPTZ,
    seller_archived_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_conversations_goods_buyer_seller UNIQUE (goods_id, buyer_id, seller_id),
    CONSTRAINT ck_conversations_status CHECK (status IN ('NORMAL', 'ARCHIVED', 'BLOCKED')),
    CONSTRAINT ck_conversations_parties CHECK (buyer_id <> seller_id)
);

CREATE INDEX idx_conversations_buyer_updated
    ON conversations (buyer_id, updated_at DESC);

CREATE INDEX idx_conversations_seller_updated
    ON conversations (seller_id, updated_at DESC);

CREATE TABLE system_message_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES conversations (id) ON DELETE CASCADE,
    card_type VARCHAR(40) NOT NULL,
    amount NUMERIC(12,2),
    payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    action_status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
    created_by_user_id BIGINT REFERENCES users (id),
    acted_by_user_id BIGINT REFERENCES users (id),
    created_by_system BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ,
    acted_at TIMESTAMPTZ,
    CONSTRAINT ck_system_message_cards_type CHECK (card_type IN ('BARGAIN_OFFER', 'ORDER_CARD', 'PAYMENT_CARD', 'SYSTEM_NOTICE')),
    CONSTRAINT ck_system_message_cards_status CHECK (action_status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'CANCELLED')),
    CONSTRAINT ck_system_message_cards_amount CHECK (amount IS NULL OR amount >= 0.01)
);

CREATE INDEX idx_system_message_cards_conversation_created
    ON system_message_cards (conversation_id, created_at DESC, id DESC);

CREATE INDEX idx_system_message_cards_bargain_lookup
    ON system_message_cards (id, conversation_id, action_status)
    WHERE card_type = 'BARGAIN_OFFER';

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES conversations (id) ON DELETE CASCADE,
    sender_id BIGINT REFERENCES users (id),
    message_type VARCHAR(40) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'SENT',
    text_content VARCHAR(2000),
    card_id BIGINT REFERENCES system_message_cards (id),
    sent_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    recalled_at TIMESTAMPTZ,
    CONSTRAINT ck_messages_type CHECK (message_type IN ('TEXT', 'SYSTEM_CARD')),
    CONSTRAINT ck_messages_status CHECK (status IN ('SENT', 'READ', 'RECALLED')),
    CONSTRAINT ck_messages_content CHECK (
        (message_type = 'TEXT' AND sender_id IS NOT NULL AND text_content IS NOT NULL AND card_id IS NULL)
        OR
        (message_type = 'SYSTEM_CARD' AND card_id IS NOT NULL)
    )
);

CREATE INDEX idx_messages_conversation_sent
    ON messages (conversation_id, sent_at, id);

ALTER TABLE conversations
    ADD CONSTRAINT fk_conversations_last_message
    FOREIGN KEY (last_message_id) REFERENCES messages (id);

CREATE TABLE message_read_states (
    message_id BIGINT NOT NULL REFERENCES messages (id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    read_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (message_id, user_id)
);

CREATE INDEX idx_message_read_states_user_read
    ON message_read_states (user_id, read_at DESC);

ALTER TABLE trade_orders
    ADD CONSTRAINT fk_trade_orders_conversation
    FOREIGN KEY (conversation_id) REFERENCES conversations (id);

ALTER TABLE trade_orders
    ADD CONSTRAINT fk_trade_orders_accepted_bargain_card
    FOREIGN KEY (accepted_bargain_card_id) REFERENCES system_message_cards (id);

ALTER TABLE notifications
    DROP CONSTRAINT IF EXISTS ck_notifications_type;

ALTER TABLE notifications
    ADD CONSTRAINT ck_notifications_type CHECK (type IN (
        'ORDER_CREATED',
        'ORDER_SELLER_CONFIRMED',
        'PAYMENT_ESCROWED',
        'COMPLETION_REQUESTED',
        'ORDER_COMPLETED',
        'SETTLEMENT_STATUS_CHANGED',
        'REPORT_SUBMITTED',
        'REPORT_RESOLVED',
        'APPEAL_REVIEWED',
        'REFUND_STATUS_CHANGED',
        'PENALTY_APPLIED',
        'MESSAGE_RECEIVED',
        'BARGAIN_OFFERED',
        'BARGAIN_ACCEPTED',
        'BARGAIN_REJECTED'
    ));
