ALTER TABLE stored_files
    DROP CONSTRAINT IF EXISTS ck_stored_files_file_kind;

ALTER TABLE stored_files
    ADD CONSTRAINT ck_stored_files_file_kind
    CHECK (file_kind IN (
        'AVATAR',
        'GOODS_IMAGE',
        'CAMPUS_AUTH_MATERIAL',
        'ORDER_EVIDENCE',
        'REPORT_EVIDENCE',
        'APPEAL_EVIDENCE',
        'MESSAGE_IMAGE'
    ));

ALTER TABLE stored_files
    DROP CONSTRAINT IF EXISTS ck_stored_files_message_image_participants;

ALTER TABLE stored_files
    ADD CONSTRAINT ck_stored_files_message_image_participants
    CHECK (file_kind <> 'MESSAGE_IMAGE' OR visibility_scope = 'PARTICIPANTS');

ALTER TABLE messages
    DROP CONSTRAINT IF EXISTS ck_messages_type;

ALTER TABLE messages
    ADD CONSTRAINT ck_messages_type CHECK (message_type IN ('TEXT', 'IMAGE', 'SYSTEM_CARD'));

ALTER TABLE messages
    DROP CONSTRAINT IF EXISTS ck_messages_content;

ALTER TABLE messages
    ADD CONSTRAINT ck_messages_content CHECK (
        (message_type = 'TEXT' AND sender_id IS NOT NULL AND text_content IS NOT NULL AND card_id IS NULL)
        OR
        (message_type = 'IMAGE' AND sender_id IS NOT NULL AND card_id IS NULL)
        OR
        (message_type = 'SYSTEM_CARD' AND card_id IS NOT NULL)
    );

CREATE TABLE message_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES messages (id) ON DELETE CASCADE,
    file_id BIGINT NOT NULL REFERENCES stored_files (id),
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_message_attachments_message_file UNIQUE (message_id, file_id)
);

CREATE INDEX idx_message_attachments_message
    ON message_attachments (message_id, sort_order, id);

CREATE INDEX idx_message_attachments_file
    ON message_attachments (file_id);

CREATE INDEX idx_messages_conversation_id
    ON messages (conversation_id, id);

CREATE INDEX idx_conversations_buyer_archived
    ON conversations (buyer_id, buyer_archived_at, updated_at DESC);

CREATE INDEX idx_conversations_seller_archived
    ON conversations (seller_id, seller_archived_at, updated_at DESC);
