-- ========================================================================
-- V19: AI 发布辅助能力（ai_assist_records + 系统配置）
-- ========================================================================
-- 设计目标：
--   1. 引入大模型辅助能力，帮助卖家在发布商品前做内容优化和合规自查。
--   2. AI 定位为"辅助建议"，不替代审核员决策——所有优化结果仅供卖家参考。
--   3. 通过 system_configs 限制每用户每日调用次数，防止滥用和成本失控。
--   4. 每次 AI 调用的输入/输出完整持久化，支持：
--      a) 用户查看历史优化记录
--      b) 运营分析 AI 辅助效果（采纳率、风险命中率）
--      c) 误判回溯与模型调优
-- ========================================================================

-- ------------------------------------------------------------------------
-- AI 辅助记录表
-- 设计要点：
--   - 每条记录对应一次完整的 AI 辅助调用（用户点击"AI 优化"按钮）
--   - 同时记录输入（原始内容）和输出（优化建议 + 风险扫描结果）
--   - 三个核心功能：
--     ① 标题/描述优化：optimized_title, optimized_description
--     ② 分类与标签推荐：suggested_category_code, suggested_tags_json
--     ③ 内容风险扫描：risk_level, risk_reasons_json
--   - audit_reminder 字段硬编码为固定文案，向用户声明"AI 仅辅助，不替代审核"
--     这是一个安全设计约束，防止用户误以为"AI 通过了就一定能发布"
--   - recommendation_reason：优化理由说明，提升用户信任度和采纳意愿
-- ------------------------------------------------------------------------
CREATE TABLE ai_assist_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),            -- 发起 AI 辅助请求的用户

    -- === 场景标识 ===
    scenario VARCHAR(40) NOT NULL,                            -- 业务场景，当前固定为 'GOODS_ASSIST'

    -- === 用户输入（原始内容）===
    input_title VARCHAR(120),                                 -- 卖家原始输入的标题
    input_description TEXT,                                   -- 卖家原始输入的描述
    input_price NUMERIC(12,2),                                -- 卖家输入的价格（用于价格合理性辅助判断）

    -- === AI 输出（① 内容优化）===
    optimized_title VARCHAR(120),                             -- AI 优化后的标题建议
    optimized_description TEXT,                               -- AI 优化后的描述建议

    -- === AI 输出（② 分类与标签推荐）===
    suggested_category_code VARCHAR(60),                      -- AI 推荐的商品分类代码（如 'DIGITAL'、'BOOKS'）
    suggested_tags_json JSONB NOT NULL DEFAULT '[]'::jsonb,  -- AI 推荐的标签列表（JSON 数组）

    -- === AI 输出（③ 风险扫描）===
    risk_level VARCHAR(20) NOT NULL DEFAULT 'LOW',            -- 风险等级：LOW / MEDIUM / HIGH
    risk_reasons_json JSONB NOT NULL DEFAULT '[]'::jsonb,     -- 风险原因列表（JSON 数组，含具体违规点）

    -- === 优化建议说明 ===
    recommendation_reason VARCHAR(500),                       -- AI 给出的优化理由（如"标题更吸引人"）

    -- === 安全提示（硬编码，不可被 AI 响应覆盖）===
    -- 这条提示始终显示给用户，防止用户误以为 AI 通过了审核就一定能发布
    audit_reminder VARCHAR(255) NOT NULL DEFAULT
        'AI 仅提供辅助建议，不会自动审核、下架或处罚。',

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- scenario 枚举：当前仅支持商品发布辅助场景，后续可扩展（如 COMMENT_ASSIST）
    CONSTRAINT ck_ai_assist_records_scenario CHECK (
        scenario IN ('GOODS_ASSIST')
    ),
    -- risk_level 枚举：LOW(低风险)/MEDIUM(中风险)/HIGH(高风险)
    CONSTRAINT ck_ai_assist_records_risk CHECK (
        risk_level IN ('LOW', 'MEDIUM', 'HIGH')
    )
);

-- 查询某用户在某个场景下的历史 AI 辅助记录（按时间倒序）
CREATE INDEX idx_ai_assist_records_user_scenario_created
    ON ai_assist_records (user_id, scenario, created_at DESC);

-- ------------------------------------------------------------------------
-- 系统配置：AI 每日调用次数限制
-- 设计要点：
--   - 通过 system_configs 表动态管理，无需修改代码或重启服务
--   - config_key: 'ai.goods_assist.daily_limit'
--   - config_value: '5'（每用户每天最多 5 次 AI 辅助调用）
--   - 限制原因：
--     a) 防止恶意用户刷 API 导致大模型费用失控
--     b) 校园场景下 5 次/天已满足合理使用需求
--   - 可在管理后台修改该值，即时生效
-- ------------------------------------------------------------------------
INSERT INTO system_configs (config_key, config_value, value_type, description)
VALUES (
    'ai.goods_assist.daily_limit',
    '5',
    'NUMBER',
    '每个用户每天可使用 AI 商品发布辅助的次数'
)
ON CONFLICT (config_key) DO UPDATE
SET config_value = EXCLUDED.config_value,
    value_type = EXCLUDED.value_type,
    description = EXCLUDED.description,
    updated_at = now();