CREATE TABLE ai_assist_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    scenario VARCHAR(40) NOT NULL,
    input_title VARCHAR(120),
    input_description TEXT,
    input_price NUMERIC(12,2),
    optimized_title VARCHAR(120),
    optimized_description TEXT,
    suggested_category_code VARCHAR(60),
    suggested_tags_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    risk_level VARCHAR(20) NOT NULL DEFAULT 'LOW',
    risk_reasons_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    recommendation_reason VARCHAR(500),
    audit_reminder VARCHAR(255) NOT NULL DEFAULT 'AI 仅提供辅助建议，不会自动审核、下架或处罚。',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_ai_assist_records_scenario CHECK (scenario IN ('GOODS_ASSIST')),
    CONSTRAINT ck_ai_assist_records_risk CHECK (risk_level IN ('LOW', 'MEDIUM', 'HIGH'))
);

CREATE INDEX idx_ai_assist_records_user_scenario_created
    ON ai_assist_records (user_id, scenario, created_at DESC);

INSERT INTO system_configs (config_key, config_value, value_type, description)
VALUES ('ai.goods_assist.daily_limit', '5', 'NUMBER', '每个用户每天可使用 AI 商品发布辅助的次数')
ON CONFLICT (config_key) DO UPDATE
SET config_value = EXCLUDED.config_value,
    value_type = EXCLUDED.value_type,
    description = EXCLUDED.description,
    updated_at = now();
