CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    nickname VARCHAR(80) NOT NULL,
    phone VARCHAR(40),
    personal_email VARCHAR(160),
    avatar_file_id BIGINT,
    public_department_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    account_status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    alumni_flag BOOLEAN NOT NULL DEFAULT FALSE,
    disabled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT ck_users_account_status CHECK (account_status IN ('ACTIVE', 'LOCKED', 'DISABLED'))
);

CREATE TABLE stored_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_bucket VARCHAR(120) NOT NULL,
    storage_key VARCHAR(512) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(120) NOT NULL,
    byte_size BIGINT NOT NULL,
    checksum VARCHAR(128) NOT NULL,
    file_kind VARCHAR(60) NOT NULL,
    visibility_scope VARCHAR(40) NOT NULL,
    owner_user_id BIGINT,
    business_type VARCHAR(80),
    business_id BIGINT,
    audit_status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT uq_stored_files_storage_key UNIQUE (storage_bucket, storage_key),
    CONSTRAINT ck_stored_files_byte_size CHECK (byte_size >= 0),
    CONSTRAINT ck_stored_files_visibility CHECK (visibility_scope IN ('PUBLIC', 'PRIVATE', 'PARTICIPANTS', 'ADMIN_ONLY')),
    CONSTRAINT ck_stored_files_audit_status CHECK (audit_status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

ALTER TABLE users
    ADD CONSTRAINT fk_users_avatar_file FOREIGN KEY (avatar_file_id) REFERENCES stored_files (id);

ALTER TABLE stored_files
    ADD CONSTRAINT fk_stored_files_owner_user FOREIGN KEY (owner_user_id) REFERENCES users (id);

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(60) NOT NULL,
    name VARCHAR(80) NOT NULL,
    description TEXT,
    CONSTRAINT uq_roles_code UNIQUE (code)
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL REFERENCES users (id),
    role_id BIGINT NOT NULL REFERENCES roles (id),
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    assigned_by_admin_id BIGINT REFERENCES users (id),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE user_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    session_token_hash VARCHAR(128) NOT NULL,
    last_active_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    absolute_expires_at TIMESTAMPTZ NOT NULL,
    ip_address INET,
    user_agent TEXT,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_user_sessions_token_hash UNIQUE (session_token_hash)
);

CREATE INDEX idx_user_sessions_user_active
    ON user_sessions (user_id, expires_at)
    WHERE revoked_at IS NULL;

CREATE TABLE campus_places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus VARCHAR(120) NOT NULL,
    name VARCHAR(120) NOT NULL,
    detail VARCHAR(255),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_campus_places_campus_name UNIQUE (campus, name)
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT REFERENCES categories (id),
    name VARCHAR(120) NOT NULL,
    code VARCHAR(80) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    prohibited_flag BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_categories_code UNIQUE (code)
);

CREATE INDEX idx_categories_parent_enabled ON categories (parent_id, enabled, sort_order);

CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    description VARCHAR(255),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_tags_name UNIQUE (name)
);

CREATE TABLE system_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key VARCHAR(120) NOT NULL,
    config_value TEXT NOT NULL,
    value_type VARCHAR(30) NOT NULL,
    description TEXT,
    updated_by_admin_id BIGINT REFERENCES users (id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_system_configs_key UNIQUE (config_key),
    CONSTRAINT ck_system_configs_value_type CHECK (value_type IN ('STRING', 'NUMBER', 'BOOLEAN', 'JSON', 'DURATION'))
);

CREATE TABLE operation_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT REFERENCES users (id),
    action VARCHAR(120) NOT NULL,
    target_type VARCHAR(80) NOT NULL,
    target_id BIGINT,
    before_json JSONB,
    after_json JSONB,
    ip_address INET,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_operation_logs_target ON operation_logs (target_type, target_id, created_at DESC);
CREATE INDEX idx_operation_logs_admin ON operation_logs (admin_id, created_at DESC);

CREATE TABLE sensitive_access_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT REFERENCES users (id),
    target_type VARCHAR(80) NOT NULL,
    target_id BIGINT NOT NULL,
    reason TEXT NOT NULL,
    result VARCHAR(40) NOT NULL,
    ip_address INET,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_sensitive_access_logs_result CHECK (result IN ('ALLOWED', 'DENIED', 'FAILED'))
);

CREATE INDEX idx_sensitive_access_logs_target ON sensitive_access_logs (target_type, target_id, created_at DESC);
CREATE INDEX idx_sensitive_access_logs_admin ON sensitive_access_logs (admin_id, created_at DESC);
