-- V23: 身份整改批次 —— 账号管理、密码找回令牌、校园邮箱后缀放宽。

CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    token_hash VARCHAR(128) NOT NULL,
    requested_email VARCHAR(160) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_password_reset_tokens_hash UNIQUE (token_hash)
);

CREATE INDEX idx_password_reset_tokens_user_active
    ON password_reset_tokens (user_id, expires_at)
    WHERE consumed_at IS NULL;

INSERT INTO system_configs (config_key, config_value, value_type, description)
VALUES
    (
        'campus.auth.email_suffixes',
        '["example.edu","edu.cn","student.edu","campus.edu","university.edu","school.edu"]',
        'JSON',
        '校园邮箱后缀白名单；支持常见 edu / edu.cn / student / campus 域名，仍由认证服务按配置匹配。'
    )
ON CONFLICT (config_key) DO UPDATE
SET config_value = EXCLUDED.config_value,
    value_type = EXCLUDED.value_type,
    description = EXCLUDED.description,
    updated_at = now();
