CREATE TABLE campus_auths (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    real_name VARCHAR(80),
    student_no VARCHAR(80),
    department VARCHAR(120),
    campus_email VARCHAR(160),
    score INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    reviewed_by_admin_id BIGINT REFERENCES users (id),
    reviewed_at TIMESTAMPTZ,
    failure_reason TEXT,
    identity_claim_key VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_campus_auths_user UNIQUE (user_id),
    CONSTRAINT ck_campus_auths_score CHECK (score BETWEEN 0 AND 100),
    CONSTRAINT ck_campus_auths_status CHECK (status IN ('DRAFT', 'ACCUMULATING', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'INVALID'))
);

CREATE INDEX idx_campus_auths_status_updated
    ON campus_auths (status, updated_at DESC, id DESC);

CREATE UNIQUE INDEX idx_campus_auths_campus_email_unique
    ON campus_auths (lower(campus_email))
    WHERE campus_email IS NOT NULL;

CREATE UNIQUE INDEX idx_campus_auths_identity_claim_unique
    ON campus_auths (identity_claim_key)
    WHERE identity_claim_key IS NOT NULL;

CREATE TABLE campus_auth_factors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus_auth_id BIGINT NOT NULL REFERENCES campus_auths (id) ON DELETE CASCADE,
    factor_type VARCHAR(40) NOT NULL,
    score_value INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    submitted_value TEXT,
    stored_file_id BIGINT REFERENCES stored_files (id),
    email_token_hash VARCHAR(128),
    email_token_expires_at TIMESTAMPTZ,
    reviewed_by_admin_id BIGINT REFERENCES users (id),
    reviewed_at TIMESTAMPTZ,
    rejected_reason TEXT,
    submit_count_24h INTEGER NOT NULL DEFAULT 0,
    submit_window_started_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_campus_auth_factors_type UNIQUE (campus_auth_id, factor_type),
    CONSTRAINT ck_campus_auth_factors_score CHECK (score_value BETWEEN 0 AND 100),
    CONSTRAINT ck_campus_auth_factors_submit_count CHECK (submit_count_24h >= 0),
    CONSTRAINT ck_campus_auth_factors_type CHECK (factor_type IN ('NAME_STUDENT_NO', 'DEPARTMENT', 'CAMPUS_EMAIL', 'STUDENT_CARD', 'CAMPUS_CARD')),
    CONSTRAINT ck_campus_auth_factors_status CHECK (status IN ('PENDING', 'VERIFIED', 'REJECTED', 'EXPIRED'))
);

CREATE INDEX idx_campus_auth_factors_auth
    ON campus_auth_factors (campus_auth_id, factor_type);

CREATE INDEX idx_campus_auth_factors_file
    ON campus_auth_factors (stored_file_id)
    WHERE stored_file_id IS NOT NULL;

CREATE TABLE campus_auth_factor_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus_auth_factor_id BIGINT NOT NULL REFERENCES campus_auth_factors (id) ON DELETE CASCADE,
    stored_file_id BIGINT NOT NULL REFERENCES stored_files (id),
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_campus_auth_factor_files_pair UNIQUE (campus_auth_factor_id, stored_file_id),
    CONSTRAINT uq_campus_auth_factor_files_file UNIQUE (stored_file_id)
);

CREATE INDEX idx_campus_auth_factor_files_factor
    ON campus_auth_factor_files (campus_auth_factor_id, sort_order, id);

CREATE INDEX idx_campus_auth_factor_files_file
    ON campus_auth_factor_files (stored_file_id);
