-- ========================================================================
-- V9: 商品目录体系（goods / goods_images / goods_tags）+ 全文搜索触发器
-- ========================================================================
-- 设计目标：
--   1. 将商品核心属性与图片、标签解耦，各自独立建表。
--      - goods: 标题、描述、成色、价格、状态机等核心字段。
--      - goods_images: 支持多图、排序、主图唯一约束。
--      - goods_tags: M:N 关联，后续可按标签聚类推荐。
--   2. 双状态机（status + audit_status）协同控制商品公网可见性：
--      - status（商品状态）: DRAFT → PENDING_REVIEW → ON_SALE/RESERVED/SOLD...
--      - audit_status（审核状态）: NOT_SUBMITTED → PENDING → APPROVED/REJECTED
--      只有 status='ON_SALE' AND audit_status='APPROVED' AND is_deleted=FALSE
--      的商品才能被公网列表查询暴露。
--   3. search_vector（全文检索向量）由数据库触发器自动维护，
--      应用层无需显式同步，避免数据不一致。
--   4. 所有 CHECK 约束均在数据库层强制执行，防御应用层 Bug。
-- ========================================================================

-- ------------------------------------------------------------------------
-- 商品主表
-- 核心设计：
--   - status 表示业务生命周期（草稿→在售→售出等）
--   - audit_status 表示合规审核生命周期（未提交→待审→通过/拒绝）
--   - 两者独立演进：卖家可把商品设为 DRAFT 同时处于 APPROVED 状态，
--     也可 ON_SALE 但 PENDING 审核（此时对外不可见）
--   - current_occupied_order_id 用于乐观锁占位，防止一物多卖
--   - search_vector 由触发器自动填充，禁止应用层直接写入
--   - is_deleted 实现软删除，保留历史数据用于审计追溯
-- ------------------------------------------------------------------------
CREATE TABLE goods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id BIGINT NOT NULL REFERENCES users (id),          -- 卖家外键，关联 users 表
    category_id BIGINT NOT NULL REFERENCES categories (id),   -- 分类外键，关联 categories 表
    title VARCHAR(80) NOT NULL,                               -- 商品标题，2~80 字符
    description TEXT NOT NULL,                                -- 商品描述，10~2000 字符
    condition_level VARCHAR(40) NOT NULL,                     -- 成色：全新/几乎全新/轻微使用/明显使用
    list_price NUMERIC(12,2) NOT NULL,                        -- 标价，精度 2 位小数，≥0.01
    trade_place_id BIGINT REFERENCES campus_places (id),      -- 面交地点外键（可选）
    trade_place_detail VARCHAR(255),                          -- 面交地点补充描述（可选，如"图书馆门口"）
    available_time_text VARCHAR(255),                         -- 可交易时间文字说明（如"工作日晚上"）
    status VARCHAR(40) NOT NULL DEFAULT 'DRAFT',              -- 商品业务状态，默认草稿
    audit_status VARCHAR(40) NOT NULL DEFAULT 'NOT_SUBMITTED',-- 审核状态，默认未提交
    current_occupied_order_id BIGINT,                         -- 当前占用该商品的订单 ID（防止超卖）
    search_vector TSVECTOR,                                   -- 全文搜索向量，由触发器自动填充
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,                -- 软删除标记
    published_at TIMESTAMPTZ,                                 -- 正式发布时间
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- === 约束 ===
    -- 成色枚举：NEW(全新) LIKE_NEW(几乎全新) LIGHTLY_USED(轻微使用) NOTICEABLY_USED(明显使用)
    CONSTRAINT ck_goods_condition_level CHECK (
        condition_level IN ('NEW', 'LIKE_NEW', 'LIGHTLY_USED', 'NOTICEABLY_USED')
    ),
    -- 商品状态机：DRAFT→PENDING_REVIEW→ON_SALE→RESERVED→SOLD，或中途 OFF_SHELF/DELETED
    CONSTRAINT ck_goods_status CHECK (
        status IN ('DRAFT', 'PENDING_REVIEW', 'ON_SALE', 'RESERVED', 'SOLD', 'OFF_SHELF', 'DELETED')
    ),
    -- 审核状态机：NOT_SUBMITTED→PENDING→APPROVED/REJECTED
    CONSTRAINT ck_goods_audit_status CHECK (
        audit_status IN ('NOT_SUBMITTED', 'PENDING', 'APPROVED', 'REJECTED')
    ),
    -- 价格底线：防止 0 元或负价商品
    CONSTRAINT ck_goods_price CHECK (list_price >= 0.01),
    -- 标题长度：至少 2 字符，最多 80 字符（适配移动端展示）
    CONSTRAINT ck_goods_title_length CHECK (char_length(title) BETWEEN 2 AND 80),
    -- 描述长度：至少 10 字符（防止无意义商品），最多 2000 字符
    CONSTRAINT ck_goods_description_length CHECK (char_length(description) BETWEEN 10 AND 2000)
);

-- ------------------------------------------------------------------------
-- 商品图片关联表
-- 设计要点：
--   - 与 goods 主表解耦，每件商品可有 N 张图片
--   - sort_order 控制前端展示顺序（升序）
--   - is_primary 标记主图，通过部分唯一索引保证每个 goods 仅一条主图
--   - ON DELETE CASCADE：商品删除时自动清理关联图片记录
--   - UNIQUE(goods_id, file_id)：防止同一文件被重复关联到同一商品
-- ------------------------------------------------------------------------
CREATE TABLE goods_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goods_id BIGINT NOT NULL REFERENCES goods (id) ON DELETE CASCADE, -- 商品外键，级联删除
    file_id BIGINT NOT NULL REFERENCES stored_files (id),    -- 文件外键，关联存储系统
    sort_order INTEGER NOT NULL DEFAULT 0,                   -- 排序号，升序展示，0 排最前
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,               -- 是否为主图
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- 同一商品下同一文件不能重复关联
    CONSTRAINT uq_goods_images_pair UNIQUE (goods_id, file_id),
    -- sort_order 不能为负数
    CONSTRAINT ck_goods_images_sort_order CHECK (sort_order >= 0)
);

-- 部分唯一索引：每个 goods 最多只有一行 is_primary = TRUE
-- 这比应用层保证更可靠——数据库层直接拦截并发冲突
CREATE UNIQUE INDEX uq_goods_images_primary
    ON goods_images (goods_id)
    WHERE is_primary = TRUE;

-- 反向索引：通过 file_id 快速查找关联的商品（用于文件被删除时的级联清理）
CREATE INDEX idx_goods_images_file
    ON goods_images (file_id);

-- ------------------------------------------------------------------------
-- 商品-标签关联表（M:N）
-- 设计要点：
--   - 联合主键 (goods_id, tag_id)，天然去重
--   - ON DELETE CASCADE：商品删除时自动清理标签关联
--   - 与 goods 主表解耦，后续可按标签做聚类推荐、热门标签统计
-- ------------------------------------------------------------------------
CREATE TABLE goods_tags (
    goods_id BIGINT NOT NULL REFERENCES goods (id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES tags (id),
    PRIMARY KEY (goods_id, tag_id)
);

-- ========================================================================
-- 全文搜索触发器：自动维护 search_vector 列
-- ========================================================================
-- 设计优势：
--   1. 应用层零感知——Java 代码完全不需要显式更新 search_vector
--   2. 数据一致性由数据库保证——任何 INSERT/UPDATE title/description
--      都会触发向量重建，不会出现"搜索不到刚更新的商品"
--   3. 使用 'simple' 配置（非特定语言），避免中文分词器依赖，
--      配合 pg_trgm 模糊匹配索引实现混合搜索
--   4. updated_at 也由触发器自动更新，确保修改时间精确反映最后变更
-- ========================================================================

CREATE OR REPLACE FUNCTION refresh_goods_search_vector()
RETURNS trigger AS $$
BEGIN
    -- 将 title 和 description 拼接后转为 tsvector 全文搜索向量
    -- COALESCE 处理空值情况（虽然 title 是 NOT NULL，但防御性写法无副作用）
    -- 'simple' 配置：不做停用词过滤和语言词干提取，保留完整关键词
    NEW.search_vector :=
        to_tsvector('simple', COALESCE(NEW.title, '') || ' ' || COALESCE(NEW.description, ''));
    -- 同步更新 updated_at 时间戳
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 触发器：在 INSERT 或 UPDATE title/description 之前自动执行
-- "UPDATE OF title, description" 表示仅当这两个列发生变化时才触发，
-- 避免修改其他字段（如 status、list_price）时的不必要的 tsvector 重算
CREATE TRIGGER trg_goods_refresh_search_vector
BEFORE INSERT OR UPDATE OF title, description
ON goods
FOR EACH ROW
EXECUTE FUNCTION refresh_goods_search_vector();