CREATE TABLE goods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id BIGINT NOT NULL REFERENCES users (id),
    category_id BIGINT NOT NULL REFERENCES categories (id),
    title VARCHAR(80) NOT NULL,
    description TEXT NOT NULL,
    condition_level VARCHAR(40) NOT NULL,
    list_price NUMERIC(12,2) NOT NULL,
    trade_place_id BIGINT REFERENCES campus_places (id),
    trade_place_detail VARCHAR(255),
    available_time_text VARCHAR(255),
    status VARCHAR(40) NOT NULL DEFAULT 'DRAFT',
    audit_status VARCHAR(40) NOT NULL DEFAULT 'NOT_SUBMITTED',
    current_occupied_order_id BIGINT,
    search_vector TSVECTOR,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_goods_condition_level CHECK (condition_level IN ('NEW', 'LIKE_NEW', 'LIGHTLY_USED', 'NOTICEABLY_USED')),
    CONSTRAINT ck_goods_status CHECK (status IN ('DRAFT', 'PENDING_REVIEW', 'ON_SALE', 'RESERVED', 'SOLD', 'OFF_SHELF', 'DELETED')),
    CONSTRAINT ck_goods_audit_status CHECK (audit_status IN ('NOT_SUBMITTED', 'PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_goods_price CHECK (list_price >= 0.01),
    CONSTRAINT ck_goods_title_length CHECK (char_length(title) BETWEEN 2 AND 80),
    CONSTRAINT ck_goods_description_length CHECK (char_length(description) BETWEEN 10 AND 2000)
);

CREATE TABLE goods_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goods_id BIGINT NOT NULL REFERENCES goods (id) ON DELETE CASCADE,
    file_id BIGINT NOT NULL REFERENCES stored_files (id),
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_goods_images_pair UNIQUE (goods_id, file_id),
    CONSTRAINT ck_goods_images_sort_order CHECK (sort_order >= 0)
);

CREATE UNIQUE INDEX uq_goods_images_primary
    ON goods_images (goods_id)
    WHERE is_primary = TRUE;

CREATE INDEX idx_goods_images_file
    ON goods_images (file_id);

CREATE TABLE goods_tags (
    goods_id BIGINT NOT NULL REFERENCES goods (id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES tags (id),
    PRIMARY KEY (goods_id, tag_id)
);

CREATE OR REPLACE FUNCTION refresh_goods_search_vector()
RETURNS trigger AS $$
BEGIN
    NEW.search_vector :=
        to_tsvector('simple', COALESCE(NEW.title, '') || ' ' || COALESCE(NEW.description, ''));
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_goods_refresh_search_vector
BEFORE INSERT OR UPDATE OF title, description
ON goods
FOR EACH ROW
EXECUTE FUNCTION refresh_goods_search_vector();
