// 文件功能：定义站内通知事件类型，需与 Flyway 中 notifications.type 的 CHECK 约束保持一致。
package com.campusresale.notification;

public enum NotificationType {
    ORDER_CREATED,
    ORDER_SELLER_CONFIRMED,
    PAYMENT_ESCROWED,
    COMPLETION_REQUESTED,
    ORDER_COMPLETED,
    REVIEW_SUBMITTED,
    SETTLEMENT_STATUS_CHANGED,
    REPORT_SUBMITTED,
    REPORT_RESOLVED,
    APPEAL_REVIEWED,
    REFUND_STATUS_CHANGED,
    PENALTY_APPLIED,
    AI_REVIEW_REMINDER,
    MESSAGE_RECEIVED,
    BARGAIN_OFFERED,
    BARGAIN_ACCEPTED,
    BARGAIN_REJECTED
}
