package com.campusresale.notification;

public enum NotificationType {
    ORDER_CREATED,
    ORDER_SELLER_CONFIRMED,
    PAYMENT_ESCROWED,
    COMPLETION_REQUESTED,
    ORDER_COMPLETED,
    REVIEW_SUBMITTED,
    SETTLEMENT_STATUS_CHANGED,
    REPORT_SUBMITTED,
    REPORT_RESOLVED,
    APPEAL_REVIEWED,
    REFUND_STATUS_CHANGED,
    PENALTY_APPLIED,
    AI_REVIEW_REMINDER,
    MESSAGE_RECEIVED,
    BARGAIN_OFFERED,
    BARGAIN_ACCEPTED,
    BARGAIN_REJECTED
}
